version: '3.9'
services:
  redis:
    image: redis

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/api
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - shared_tmp:/app/tmp
    working_dir: /app/api
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - shared_tmp:/app/tmp
    working_dir: /app/bot
    environment:
      - PYTHONPATH=/app
      - REDIS_URL_BOT=redis://redis:6379/3
    command: uvicorn telegram_bot:app --host 0.0.0.0 --port 8080
    depends_on:
      - api

volumes:
  shared_tmp: